import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import data from "@/source/mockData";

import { Swiper, SwiperSlide } from 'swiper/react'
import { Scrollbar, Navigation } from 'swiper/modules';

import 'swiper/css';
import 'swiper/css/scrollbar';
import 'swiper/css/navigation';
import { useState } from 'react';

export default function Home() {
  const [mySwiper, setMySwiper] = useState({});

  let isRoundSheet = false;

  function randomSheet() {
    const sheets = [
      styles.leftSheet,
      styles.rightSheet,
      styles.round,
    ];

    if (isRoundSheet) {
      isRoundSheet = false;
      sheets.pop();
    }

    let sheet = sheets[Math.round(Math.random() * (sheets.length - 1))];

    if (sheet == styles.round) {
      isRoundSheet = true;
    }

    return sheet;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Oranienbaum&family=Raleway:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <main className={`${styles.main}`}>
        <h1 className={styles.title}>Полезные материалы</h1>
        <span className={styles.description}>Собрали для вас полезные исследования схемы кормления и другие материалы, которые пригодятся для лучших результатов на вашем хозяйстве</span>
        <Swiper
          spaceBetween={0}
          slidesPerView={"auto"}
          scrollbar={{ draggable: true, horizontalClass: `${styles.scrollbar}` }}
          modules={[Scrollbar, Navigation]}
          onInit={(ev) => {
            setMySwiper(ev)
          }}
          className={styles.swiper}
        >
          {data.map(item => (
            <SwiperSlide key={item.id} className={`${styles.slide} ${item.title.length > 35 && styles.slide__long} ${randomSheet()}`}>
              <img src={item.img} alt="" />
              <p>{item.title}</p>
              <span>{item.date}</span>
            </SwiperSlide>
          ))}
        </Swiper>
        <div className={styles.navigation}>
          <button
            className={styles.navigation__prev}
            onClick={() => mySwiper.slidePrev()}
          >
            <span className={styles.desctop}>
              <svg width="181" height="47" viewBox="0 0 181 47" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect x="1" y="22" width="172" height="2.99998" fill="#7884A5" />
                <path d="M12 12V12C12 18.0751 7.07513 23 0.999998 23L-9.69627e-07 23" stroke="#7884A5" strokeWidth="3" />
                <path d="M12 35V35C12 28.9249 7.07513 24 1 24L6.11999e-07 24" stroke="#7884A5" strokeWidth="3" />
              </svg>
            </span>
            <span className={styles.mobile}>
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g clipPath="url(#clip0_2_291)">
                  <g clipPath="url(#clip1_2_291)">
                    <rect y="10.4348" width="24" height="3.13043" fill="#7884A5" />
                    <path d="M12 3.05176e-05V3.05176e-05C12 6.07516 7.07513 11 0.999996 11L-6.19952e-07 11" stroke="#7884A5" strokeWidth="3" />
                    <path d="M12 24V24C12 17.9249 7.07513 13 1 13L-4.41349e-07 13" stroke="#7884A5" strokeWidth="3" />
                  </g>
                </g>
                <defs>
                  <clipPath id="clip0_2_291">
                    <rect width="28" height="28" fill="white" />
                  </clipPath>
                  <clipPath id="clip1_2_291">
                    <rect width="24" height="24" fill="white" />
                  </clipPath>
                </defs>
              </svg>
            </span>
          </button>
          <button
            className={styles.navigation__next}
            onClick={() => mySwiper.slideNext()}
          >
            <span className={styles.desctop}>
              <svg width="181" height="47" viewBox="0 0 181 47" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect width="172" height="2.99998" transform="matrix(-1 8.74228e-08 8.74228e-08 1 172 22)" fill="#7884A5" />
                <path d="M161 12V12C161 18.0751 165.925 23 172 23L173 23" stroke="#7884A5" strokeWidth="3" />
                <path d="M161 35V35C161 28.9249 165.925 24 172 24L173 24" stroke="#7884A5" strokeWidth="3" />
              </svg>
            </span>
            <span className={styles.mobile}>
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g clipPath="url(#clip0_2_287)">
                  <g clipPath="url(#clip1_2_287)">
                    <rect width="24" height="3.13043" transform="matrix(-1 8.74228e-08 8.74228e-08 1 24 10.4348)" fill="#7884A5" />
                    <path d="M12 3.05176e-05V3.05176e-05C12 6.3393 17.139 11.4783 23.4783 11.4783L24 11.4783" stroke="#7884A5" strokeWidth="3" />
                    <path d="M12 24V24C12 17.6608 17.139 12.5218 23.4783 12.5218L24 12.5218" stroke="#7884A5" strokeWidth="3" />
                  </g>
                </g>
                <defs>
                  <clipPath id="clip0_2_287">
                    <rect width="28" height="28" fill="white" />
                  </clipPath>
                  <clipPath id="clip1_2_287">
                    <rect width="24" height="24" fill="white" />
                  </clipPath>
                </defs>
              </svg>
            </span>
          </button>
        </div>
      </main>
    </>
  )
}
